### ISSUE TITLE
Could not find a declaration file for module 'v-onboarding'

### ISSUE THREAD

**Issue by micke-dahlgren** [fatihsolhan/v-onboarding#97]
**Describe the bug**
Error TS7016 on the import line
import { VOnboardingWrapper, useVOnboarding } from '_v-onboarding_'
```
Could not find a declaration file for module 'v-onboarding'. 
'..../node_modules/v-onboarding/dist/v-onboarding.es.js' implicitly has an 'any' type.
  There are types at '..../node_modules/v-onboarding/dist/index.d.ts', 
but this result could not be resolved when respecting package.json "exports". 
The 'v-onboarding' library may need to update its package.json or typings.ts(7016)

```

**Comment by fatihsolhan** [comment]
Hi @micke-dahlgren, this issue should've been fixed with v-onboarding 2.8.1
Can you please make sure it's 2.8.1 and provide a reproduction of the issue with codesandbox?

**Comment by iolk** [comment]
Hey @fatihsolhan, I encountered the same issue after upgrading from version 2.6.0 to 2.8.1. I've managed to reproduce it using the 2.8.1: https://stackblitz.com/edit/vitejs-vite-jq9x8d

**Comment by fatihsolhan** [comment]
thank you @iolk, I'll fix it

**Comment by macJames976** [comment]
Hi, @fatihsolhan
thanks for your job; do you have any news about this problems?

Thanks

**Comment by fatihsolhan** [comment]
> Hi, @fatihsolhan
> 
> thanks for your job; do you have any news about this problems?
> 
> 
> 
> Thanks

Hey @macJames976 sorry it's been quite busy weeks so I couldn't get back to this. I'll fix it as soon as possible. Thanks for your understanding🙏🏻

**Comment by bubbzDotDev** [comment]
Experiencing this issue as well.

**Comment by bubbzDotDev** [comment]
@iolk @micke-dahlgren @macJames976

I found a workaround while using 2.8.1:

Add `declare module "v-onboarding"` to a `.d.ts` in your `src/` directory, like this: `src/v-onboarding.d.ts`

**Comment by fatihsolhan** [comment]
Hey everyone,

The issue should be fixed now. It turned out to be a simple fix in the end. Initially, I thought adding `types` to the package.json would be enough for types, but it seems I needed to include it in the exports as well for proper exporting.

I apologize for the delay in resolving this issue. Your patience is much appreciated. If you encounter any further issues, please don't hesitate to let me know.

Thanks again for your understanding!
